### ISSUE TITLE
Live USB created with unetbootin crashes

### ISSUE THREAD

**Issue by artingei** [ozonos/bug-tracker-BETA#1]
Two different USB sticks crashed during the start operation before I managed to create a working stick via command line (OS X).
Errors:
![image](https://cloud.githubusercontent.com/assets/5765780/6568675/fc9b37ac-c6db-11e4-93a3-d95f4f89cbf2.jpeg)
![foto 2](https://cloud.githubusercontent.com/assets/5765780/6568674/fc99aaea-c6db-11e4-83f4-6b21fa738f69.JPG)

**Comment by me4oslav** [comment]
This happens also with stock Fedora. Unetbootin is not a great tool to use for doing live USBs.

**Comment by Blingy** [comment]
same problem here with "Linux live usb creator"

**Comment by UriHerrera** [comment]
Don't use Unetbootin. Either use Gnome disks if you're on another Linux install with Gnome or use `dd` (`dd if=Ozon-Hydrogen-Beta.iso of=/dev/sdX` - where X is the letter assigned to the USB drive. Write it to the device, not the partition). If you're on OSX you can also use `dd`. If you're on Windows use Win32 Image Writer.
