### ISSUE TITLE
Live boot doesn't work via UEFI

### ISSUE THREAD

**Issue by DanielRamosAcosta** [ozonos/bug-tracker-BETA#20]
I putted the ISO in a pen-drive using Rufus. Here is the error:
<pre>
[     0.040407] Ignoring BGRT: invalid status 0 (expected 1)
[   ok   ] Started Show Plymouth Boot Screen.
[   ok   ] Reached target Path
[   ok   ] Reached target Basic System.
[   190.510368] dracut-initqueue[439]: Warning: Could not boot.
[   190.694414] dracut-initqueue[439]: Warning: /dev/disk/by-lablel/Ozon-Hydrogen-Beta does not exist
[   190.694623] dracut-initqueue[439]: Warning: /dev/mapper/live-rw does not exist
          Starting Dracut Emergency Shell...
Warning: /dev/disk/by-lablel/Ozon-Hydrogen-Beta does not exist
Warning: /dev/mapper/live-rw does not exist

Generating "/run/initramfs/rdsosreport.txt"

Entering emergency mode. Exit the shell to continue.
Type "journalctl" to view system logs.
You might want to save "/run/initramfs/rdsosreport.txt" to a USB stick or /boot
after mounting them and attach it to a bug report.

dracut:/# 
</pre>
I'll attach a screenshot of the error anyways. Thanks!
![screenshot](https://cloud.githubusercontent.com/assets/11427028/6909743/b7417eae-d749-11e4-8a39-dc7eb15f7209.jpg)

**Comment by UriHerrera** [comment]
Same problem, different software. https://github.com/ozonos/bug-tracker-BETA/issues/1

Use `dd`.

**Comment by DanielRamosAcosta** [comment]
It worked, thanks a lot!
