### ISSUE TITLE
duplicate chrome

### ISSUE THREAD

**Issue by mid0ri** [ozonos/bug-tracker-BETA#26]
at first the apps wont show up in the draws, i've reported on google+ already and someone told me to do alt+f2 and type in "r" to fix that issue it work, sort of and now a new problem pop up, chrome is showing as duplicate in the dock

**Comment by satya164** [comment]
It's a Chrome bug, not Ozon specific. Happens on normal GNOME Shell too.

**Comment by mid0ri** [comment]
anyway to resolve this issue? and i dont mean going into the google.desktop
file and modifying a few lines because i've tried that and it didnt work

**Comment by satya164** [comment]
@mid0ri That seems to be the only solution right now. What did you do?

**Comment by mid0ri** [comment]
ok so the duplicate did not happen unless I logout. So what i did was before logout I close ALL of chrome (ie even the hidden chrome) then when I login NO more duplicate problems and I had to update.
