### ISSUE TITLE
BTRFS installation not working

### ISSUE THREAD

**Issue by athordan** [ozonos/bug-tracker-BETA#3]
Installations using BTRFS are not working, says BTRFS skinned or something.

**Comment by UriHerrera** [comment]
Please add the *exact* error.

**Comment by athordan** [comment]
I'll try to reproduce it in a gnome box.

**Comment by athordan** [comment]
In the Box it is working. maybe it bc I am using uefi on my pc.

**Comment by athordan** [comment]
I reinstalled it with btrfs again and now it is working. Don't know what is different now. Sry, Thnx for the help anyway.
