### ISSUE TITLE
Atom shell crashes after opening Guacamelee! gold edition (via Steam)

### ISSUE THREAD

**Issue by sergioad** [ozonos/bug-tracker-BETA#6]
@me4oslav @UriHerrera @satya164 @cldx @smartfuse  I noted that while playing Guacamelee! gold edition on  Atom shell has turned into GNOME shell (all the extensions that conforms atom shell has been disabled), a fix is needed as soon as possible.

maybe this issue can apply to other Steam games.

BTW: I am really happy to help with Ozon OS :)﻿

**Comment by UriHerrera** [comment]
Logout, open a virtual terminal, use `startx &> logfile`, open the game and paste the log file here.

**Comment by sergioad** [comment]
Ok, BTW this has not happened anymore at the moment :smile:

**Comment by UriHerrera** [comment]
I'll close the issue then, comment if it's still happens.

**Comment by sergioad** [comment]
Ok, no problem :smile:
